#!/bin/bash
# gendata


# Sanity check command line options
usage() {
  printf "Usage: $0 [size]\n"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

# compile dbgen
# cd 2.18.0_rc2/dbgen/
# make clean
# make
# cd ../../

# will put the data to hdfs directory
# /tmp/tpch<size>g/
# first clear this directory on hdfs
# and drop the db on hive
hdfs_path="/tmp/tpch$1g/"
hdfs dfs -rm -r -f $hdfs_path
touch drop_db.hql
echo "drop database if exists tpch$1g cascade" > drop_db.hql
hive -f drop_db.hql

# build a directory to hold data
if [ ! -d "./data/" ]; then
    mkdir data/
fi
db_path="tpch$1g"
rm -rf data/$db_path
mkdir data/$db_path
echo $db_path

# go to tpch dbgen directory, remove previous tbl files and gen
cd 2.18.0_rc2/dbgen/
rm *.tbl
gen_data="./dbgen -s $1"
eval $gen_data

cd ../../
# pwd
mv 2.18.0_rc2/dbgen/*.tbl data/$db_path/

# make directories and put data to hdfs
hdfs dfs -mkdir $hdfs_path
hdfs dfs -mkdir /tmp/tpch$1g/customer/
hdfs dfs -mkdir /tmp/tpch$1g/lineitem/
hdfs dfs -mkdir /tmp/tpch$1g/nation/
hdfs dfs -mkdir /tmp/tpch$1g/orders/
hdfs dfs -mkdir /tmp/tpch$1g/part/
hdfs dfs -mkdir /tmp/tpch$1g/partsupp/
hdfs dfs -mkdir /tmp/tpch$1g/region/
hdfs dfs -mkdir /tmp/tpch$1g/supplier/

echo "put data to hdfs..."
hdfs dfs -put data/$db_path/customer.tbl /tmp/tpch$1g/customer/
hdfs dfs -put data/$db_path/lineitem.tbl /tmp/tpch$1g/lineitem/
hdfs dfs -put data/$db_path/nation.tbl /tmp/tpch$1g/nation/
hdfs dfs -put data/$db_path/orders.tbl /tmp/tpch$1g/orders/
hdfs dfs -put data/$db_path/part.tbl /tmp/tpch$1g/part/
hdfs dfs -put data/$db_path/partsupp.tbl /tmp/tpch$1g/partsupp/
hdfs dfs -put data/$db_path/region.tbl /tmp/tpch$1g/region/
hdfs dfs -put data/$db_path/supplier.tbl /tmp/tpch$1g/supplier/

echo "create database..."
# create database and tables on hive
touch create_db.hql
echo "CREATE DATABASE tpch$1g;" > create_db.hql
hive -f create_db.hql
# create tables;

echo "create table region..."
# region
touch create_region.hql
echo "USE tpch$1g; CREATE TABLE region (r_regionkey INT, r_name  VARCHAR(25), r_comment VARCHAR(152), r_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/region/';" > create_region.hql
hive -f create_region.hql

echo "create table nation..."
# nation
touch create_nation.hql
echo "USE tpch$1g; CREATE TABLE nation (n_nationkey INT, n_name VARCHAR(25), n_regionkey INT, n_comment VARCHAR(152), r_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/nation/';" > create_nation.hql
hive -f create_nation.hql

echo "create table customer..."
# customer
touch create_customer.hql
echo "USE tpch$1g; CREATE TABLE customer (c_custkey INT, c_name VARCHAR(25), c_address VARCHAR(40), c_nationkey INT, c_phone VARCHAR(15), c_acctbal DECIMAL, c_mktsegment VARCHAR(10), c_comment VARCHAR(117), c_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/customer/';" > create_customer.hql
hive -f create_customer.hql

echo "create table part..."
# part
touch create_part.hql
echo "USE tpch$1g; CREATE TABLE part (p_partkey INT, p_name VARCHAR(25), p_mfgr VARCHAR(25), p_brand VARCHAR(10), p_type VARCHAR(25), p_size INT, p_container VARCHAR(10), p_retailprice DECIMAL, p_comment VARCHAR(40), p_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/part/';" > create_part.hql
hive -f create_part.hql

echo "create table partsupp..."
# partsupp
touch create_partsupp.hql
echo "USE tpch$1g; CREATE TABLE partsupp (ps_partkey INT, ps_suppkey INT, ps_availqty INT, ps_supplycost DECIMAL, ps_comment VARCHAR(199), ps_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/partsupp/';" > create_partsupp.hql
hive -f create_partsupp.hql

echo "create table supplier..."
# supplier
touch create_supplier.hql
echo "USE tpch$1g; CREATE TABLE supplier (s_suppkey INT, s_name VARCHAR(25), s_address VARCHAR(40), s_nationkey INT, s_phone VARCHAR(15), s_acctbal DECIMAL, s_comment VARCHAR(101), s_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/supplier/';" > create_supplier.hql
hive -f create_supplier.hql

echo "create table lineitem..."
touch create_lineitem.hql
echo "USE tpch$1g; CREATE TABLE lineitem (l_orderkey INT, l_partkey INT, l_suppkey INT, l_linenumber INT, l_quantity DECIMAL, l_extendedprice DECIMAL, l_discount DECIMAL, l_tax DECIMAL, l_returnflag VARCHAR(1), l_linestatus VARCHAR(1), l_shipdate DATE, l_commitdate DATE, l_receiptdate DATE, l_shipinstruct VARCHAR(25), l_shipmode VARCHAR(10), l_comment VARCHAR(44), l_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/lineitem/';" > create_lineitem.hql
hive -f create_lineitem.hql

echo "create table orders..."
touch create_orders.hql
echo "USE tpch$1g; CREATE TABLE orders (o_orderkey INT, o_custkey INT, o_orderstatus VARCHAR(1), o_totalprice DECIMAL, o_orderdate DATE, o_orderpriority VARCHAR(15), o_clerk VARCHAR(15), o_shippriority INT, o_comment VARCHAR(79), o_dummy VARCHAR(10)) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE LOCATION '/tmp/tpch$1g/orders/';" > create_orders.hql
hive -f create_orders.hql



# remove all intermediate files
rm *.hql
